### ISSUE TITLE
对typescirpt有支持吗？

### ISSUE THREAD

**Issue by ShipinZ** [uni-helper/uni-helper-vscode#16]
### 描述问题

安装插件后，所有的标签全部都有个警告，看起来很烦人
![image](https://github.com/uni-helper/uni-helper-vscode/assets/51226051/5ce73cf7-5a35-4a5f-96e8-089147ebf2c6)

### 复现

```
<template>
	<view>
		<button @click="login">登录</button>
		<view>

		</view>
	</view>
</template>
```

### 系统信息

win10

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
降级到volar2.0.12或1.8.27，跟本插件无关。

**Comment by ShipinZ** [comment]
[Volar](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)已经停止支持，无法在vscode插件市场下载了。目前可以通过正常渠道下载的只有[Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar)。其中我尝试了[Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar)的2.0.12版本，但是问题依旧存在。
还有更好的解决方案吗？这个插件未来会考虑支持[Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar)吗？（受够了HBulderX的代码提示经常不翼而飞😭）

**Comment by ModyQyW** [comment]
@JoyfulAndSpeedyMan 这跟本插件无关，你需要的是 https://github.com/uni-helper/uni-app-types ，配置 tsconfig 就可以了。
